### ISSUE TITLE
Cannot connect to the metro bundle server.

### ISSUE THREAD

**Issue by mustafaibrahim989** [vgs-samples/vgs-collect-show-android-react-native-demo#7]
I am receiving this error when trying to run the App on Android emulator after integrating with VGS Show and Collect. The App is connected to metro and working fine before the VGS integration and when remove the integration from build.gradle

![](https://user-images.githubusercontent.com/57619523/158504785-67b0a8f0-50e3-4041-909e-3f249e3836f1.png)

**Comment by fansilva1991** [comment]
I'm having the same problem. Right after installing VGS SDK, same error.

<img width="349" alt="Screen Shot 2022-07-02 at 12 34 06 PM" src="https://user-images.githubusercontent.com/4633618/177006972-9a5d124b-fac9-47e9-939d-a4543d1b3a1c.png">

**Comment by fansilva1991** [comment]
@Endorf any feedbacks on that issue?

**Comment by Endorf** [comment]
Hi @fansilva1991.
The issue occurs because VGS Collect SDK doesn’t allow `cleartextTraffic` by default.
To fix this issue please add the following code to `network_security_config.xml` in your application `res/xml` folder. Please check the demo app.

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">10.0.2.2</domain>
        <domain includeSubdomains="true">10.0.1.1</domain>
        <domain includeSubdomains="true">localhost</domain>
    </domain-config>

    <base-config cleartextTrafficPermitted="false" />
</network-security-config>
```

**Comment by fansilva1991** [comment]
@Endorf, thanks; I will test this and let you know if it works.

**Comment by fansilva1991** [comment]
@Endorf, the solution you provided solved the issue! Closing it.

**Comment by mustafaibrahim989** [comment]
@Endorf It works. Thanks
