### ISSUE TITLE
React Native iOS Sample

### ISSUE THREAD

**Issue by fansilva1991** [vgs-samples/vgs-collect-show-android-react-native-demo#8]
Hi,

Do you guys have any samples for iOS integration? Since react-native is a hybrid framework, we need to integrate it on both platform, and I saw that the Flutter sample has both platform working.

Or there is any limitation related to integrate the SDK on iOS for React Native?

**Comment by dmytrokhl** [comment]
hi @fansilva1991, yes we have iOS SDKs demo in RN. Please check [this](https://github.com/vgs-samples/vgs-collect-show-ios-react-native-demo) repo.

**Comment by fansilva1991** [comment]
Hi, @dmytrokhl thanks for the information.
